name: E-Commerce CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check README file
        run: |
          if [ ! -f README.md ]; then
            echo "README.md is missing"
            exit 1
          fi

      - name: Check UI files
        run: |
          if [ ! -f ui/index.html ]; then
            echo "index.html not found"
            exit 1
          fi

          if [ ! -f ui/style.css ]; then
            echo "style.css not found"
            exit 1
          fi

      - name: Project structure
        run: ls -R
